# Default values for circleci-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

# You can extend a custom image from our runner and use
# that repository instead. See:
# https://circleci.com/docs/2.0/runner-installation-docker/#create-a-dockerfile-that-extends-the-circleci-self-hosted-runner-image
image:
  repository: circleci/runner
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  # For CircleCI Enterprise installations, see the compatible version tags here:
  # https://circleci.com/docs/2.0/runner-installation-cli/#self-hosted-runners-for-server-compatibility
  tag: "launch-agent"

configSecret:
  create: true
  name: config-values

serviceAccount:
  create: true
  name: circleci-runner
  annotations: {}
#    eks.amazonaws.com/role-arn: "arn:aws:iam:..."

# Refers to the resource class you created for your runner. See:
# https://circleci.com/docs/2.0/runner-concepts/#namespaces-and-resource-classes
resourceClass: ""
# Runner API token. See:
# https://circleci.com/docs/2.0/runner-installation-cli/#command-line-installation
runnerToken: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DBT_TGT
    value: prod
  - name: DBT_TYPE
    value: snowflake
  - name: DBT_ACCOUNT
    value: yla59983.us-east-1
  - name: DBT_USER
    value: svc_dbt
  - name: DBT_ROLE
    value: DBT_CONNECT
  - name: SNOWFLAKE_DATABASE
    value: SOURCE_TMI_SERVICES
  - name: DBT_SCHEMA
    value: public
  - name: DBT_WH
    value: DBT_WH
  - name: DBT_DB
    value: thrasio_prod
threads: 5
